# Generated by Django 4.1.7 on 2024-10-12 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_text', models.CharField(max_length=10000, null=True)),
                ('textcontent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='app.textcontent')),
            ],
        ),
    ]
