# Generated by Django 4.1.7 on 2024-10-12 21:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usertextcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContentSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('text_content_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_first', to='app.textcontent')),
                ('text_content_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_second', to='app.textcontent')),
            ],
        ),
        migrations.AddIndex(
            model_name='textcontentsimilarity',
            index=models.Index(fields=['text_content_1', 'text_content_2'], name='app_textcon_text_co_374c17_idx'),
        ),
        migrations.AddIndex(
            model_name='textcontentsimilarity',
            index=models.Index(fields=['similarity_score'], name='app_textcon_similar_8e97ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='textcontentsimilarity',
            unique_together={('text_content_1', 'text_content_2')},
        ),
    ]
